COMMAND:
# This file was generated by EventLoop GridDriver for EL job skim_PeriodD.p1328_20130719162610.full_v1_
t = AtlasTask()
t.name = 'skim_PeriodD.p1328_20130719162610.full_v1_'
t.comment += 'location:/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130719162610.full_v1_'
t.float = 200
config.Athena.EXE_MAXFILESIZE=2097152
print
print "TaskID: %d" % t.id
print "TaskContainer: %s" % t.getContainerName()

# Transform 1
trf = AtlasTransform()
trf.name = 'skim_PeriodD.p1328_20130719162610.full_v1_'
t.appendTransform(trf)
trf.initializeFromContainer('data12_8TeV.periodD.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/')
for u in trf.units: u.inputdata.names_pattern = ['*.root*']
trf.setRunLimit(8)
trf.setMinorRunLimit(4)
trf.setMajorRunLimit(4)
trf.application = Athena()
trf.application.option_file = 'runjob.sh'
trf.application.options = 'data12_8TeV.periodD.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329'
trf.application.atlas_exetype = 'EXE'
trf.application.useRootCore = True
trf.application.append_to_user_area = ['.root','.cxx','.C','.h']
trf.application.user_area_path = '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130719162610.full_v1_/elg'
trf.application.prepare()
trf.outputdata = DQ2OutputDataset()
trf.outputdata.datasetname = 'user.jayb88.skim_PeriodD.p1328_20130719162610.full_v1_'
trf.outputdata.outputdata = ['hist-output.root','output.root']
trf.copy_output = DQ2OutputDataset()
trf.copy_output.datasetname = 'user.jayb88.skim_PeriodD.p1328_20130719162610.full_v1_'
trf.copy_output.outputdata = ['hist-output.root','output.root']
trf.backend = Panda()
trf.local_location = '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130719162610.full_v1_/elg/download/data12_8TeV.periodD.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329'
trf.include_file_mask = ['hist-output.root']
trf.MB_per_job = 13000
trf.backend.requirements.excluded_sites = ['ANALY_IN2P3-CC-T2','ANALY_BNL_SHORT','ANALY_BNL_LONG','ANALY_SLAC','ANALY_GLASGOW','ANALY_INFN-NAPOLI','ANALY_ROMANIA07','ANALY_FREIBURG']

t.run()
import time
time.sleep(60)

RESPONSE:
Active server running on host 'linappserv5.pp.rhul.ac.uk'
Active server running on host 'linappserv5.pp.rhul.ac.uk' - creating kill file
COMMAND:
# This file was generated by EventLoop GridDriver for EL job skim_PeriodD.p1328_20130719164810.full_v1_
t = AtlasTask()
t.name = 'skim_PeriodD.p1328_20130719164810.full_v1_'
t.comment += 'location:/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130719164810.full_v1_'
t.float = 200
config.Athena.EXE_MAXFILESIZE=2097152
print
print "TaskID: %d" % t.id
print "TaskContainer: %s" % t.getContainerName()

# Transform 1
trf = AtlasTransform()
trf.name = 'skim_PeriodD.p1328_20130719164810.full_v1_'
t.appendTransform(trf)
trf.initializeFromContainer('data12_8TeV.periodD.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/')
for u in trf.units: u.inputdata.names_pattern = ['*.root*']
trf.setRunLimit(8)
trf.setMinorRunLimit(4)
trf.setMajorRunLimit(4)
trf.application = Athena()
trf.application.option_file = 'runjob.sh'
trf.application.options = 'data12_8TeV.periodD.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329'
trf.application.atlas_exetype = 'EXE'
trf.application.useRootCore = True
trf.application.append_to_user_area = ['.root','.cxx','.C','.h']
trf.application.user_area_path = '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130719164810.full_v1_/elg'
trf.application.prepare()
trf.outputdata = DQ2OutputDataset()
trf.outputdata.datasetname = 'user.jayb88.skim_PeriodD.p1328_20130719164810.full_v1_'
trf.outputdata.outputdata = ['hist-output.root','output.root']
trf.copy_output = DQ2OutputDataset()
trf.copy_output.datasetname = 'user.jayb88.skim_PeriodD.p1328_20130719164810.full_v1_'
trf.copy_output.outputdata = ['hist-output.root','output.root']
trf.backend = Panda()
trf.local_location = '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130719164810.full_v1_/elg/download/data12_8TeV.periodD.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329'
trf.include_file_mask = ['hist-output.root']
trf.MB_per_job = 13000
trf.backend.requirements.excluded_sites = ['ANALY_IN2P3-CC-T2','ANALY_BNL_SHORT','ANALY_BNL_LONG','ANALY_SLAC','ANALY_GLASGOW','ANALY_INFN-NAPOLI','ANALY_ROMANIA07','ANALY_FREIBURG']

t.run()
import time
time.sleep(60)

RESPONSE:
Active server running on host 'linappserv5.pp.rhul.ac.uk'
Active server running on host 'linappserv5.pp.rhul.ac.uk' - creating kill file
COMMAND:
# This file was generated by EventLoop GridDriver for EL job skim_PeriodD.p1328_20130729132955.v1
t = AtlasTask()
t.name = 'skim_PeriodD.p1328_20130729132955.v1'
t.comment += 'location:/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130729132955.v1'
t.float = 200
config.Athena.EXE_MAXFILESIZE=2097152
print
print "TaskID: %d" % t.id
print "TaskContainer: %s" % t.getContainerName()

# Transform 1
trf = AtlasTransform()
trf.name = 'skim_PeriodD.p1328_20130729132955.v1'
t.appendTransform(trf)
trf.initializeFromContainer('data12_8TeV.periodD.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/')
for u in trf.units: u.inputdata.names_pattern = ['*.root*']
trf.setRunLimit(8)
trf.setMinorRunLimit(4)
trf.setMajorRunLimit(4)
trf.application = Athena()
trf.application.option_file = 'runjob.sh'
trf.application.options = 'data12_8TeV.periodD.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329'
trf.application.atlas_exetype = 'EXE'
trf.application.useRootCore = True
trf.application.append_to_user_area = ['.root','.cxx','.C','.h']
trf.application.user_area_path = '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130729132955.v1/elg'
trf.application.prepare()
trf.outputdata = DQ2OutputDataset()
trf.outputdata.datasetname = 'user.jayb88.skim_PeriodD.p1328_20130729132955.v1'
trf.outputdata.outputdata = ['hist-output.root','output.root']
trf.copy_output = DQ2OutputDataset()
trf.copy_output.datasetname = 'user.jayb88.skim_PeriodD.p1328_20130729132955.v1'
trf.copy_output.outputdata = ['hist-output.root','output.root']
trf.backend = Panda()
trf.local_location = '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130729132955.v1/elg/download/data12_8TeV.periodD.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329'
trf.include_file_mask = ['hist-output.root']
trf.MB_per_job = 13000
trf.backend.requirements.excluded_sites = ['ANALY_IN2P3-CC-T2','ANALY_BNL_SHORT','ANALY_BNL_LONG','ANALY_SLAC','ANALY_GLASGOW','ANALY_INFN-NAPOLI','ANALY_ROMANIA07','ANALY_FREIBURG']

t.run()
import time
time.sleep(60)

RESPONSE:
Daemonising Ganga...
Daemonising Ganga...
Daemonising Ganga...
Starting server...
Starting server using command:
/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/bin/ganga -o[Configuration]RUNTIME_PATH=GangaAtlas:GangaPanda --daemon -o[PollThread]forced_shutdown_timeout=300 -o[Configuration]ServerPort=434343 -o[Configuration]ServerTimeout=1440 -o[Configuration]gangadir=/home/jblanco/gangadir-EL /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/python/GangaService/Lib/ServiceAPI/../Server/server-script.py
Waiting for server to initialise...
Server took too long to start.
No Server running
Starting server...
Starting server using command:
/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/bin/ganga -o[Configuration]RUNTIME_PATH=GangaAtlas:GangaPanda --daemon -o[PollThread]forced_shutdown_timeout=300 -o[Configuration]ServerPort=434343 -o[Configuration]ServerTimeout=1440 -o[Configuration]gangadir=/home/jblanco/gangadir-EL /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/Daemonising Ganga...
Daemonising Ganga...
Daemonising Ganga...
install/6.0.13/python/GangaService/Lib/ServiceAPI/../Server/server-script.py
Waiting for server to initialise...
Active server running on this machine.
Command sent. Waiting for output from Ganga...
[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Found 48 datasets matching data12_8TeV.periodD.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/...[0;0m
[0;33mGanga.Core.GangaRepository         : WARNING  Removing dead file linappserv0.pp.rhul.ac.uk.1375099381593.2518.session.templates.metadata.locks[0;0m
[0;33mGanga.Core.GangaRepository         : WARNING  Removing dead file linappserv0.pp.rhul.ac.uk.1375099381593.2518.session.templates.locks[0;0m
[0;33mGanga.Core.GangaRepository         : WARNING  Removing dead file linappserv0.pp.rhul.ac.uk.1375099381593.2518.session.box.metadata.locks[0;0m
[0;33mGanga.Core.GangaRepository         : WARNING  Removing dead file linappserv0.pp.rhul.ac.uk.1375099381593.2518.session.box.locks[0;0m
[0;33mGanga.Core.GangaRepository         : WARNING  Removing dead file linappserv0.pp.rhul.ac.uk.1375099381593.2518.session.tasks.locks[0;0m
[0;33mGanga.Core.GangaRepository         : WARNING  Removing dead file linappserv0.pp.rhul.ac.uk.1375099381593.2518.session.jobs.metadata.locks[0;0m
[0;33mGanga.Core.GangaRepository         : WARNING  Removing dead file linappserv0.pp.rhul.ac.uk.1375099381593.2518.session.jobs.locks[0;0m
[0;33mGanga.Core.GangaRepository         : WARNING  Removing dead file linappserv0.pp.rhul.ac.uk.1375099381593.2518.session.prep.metadata.locks[0;0m
[0;33mGanga.Core.GangaRepository         : WARNING  Removing dead file linappserv0.pp.rhul.ac.uk.1375099381593.2518.session.prep.locks[0;0m
[0;0mGanga.Core.MonitoringComponent     : INFO     Stopping the monitoring component...[0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     Preparing Athena application.[0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     Found Working Directory /nfs/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130729132955.v1/elg/inputsandbox[0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     Found ATLAS Release 17.3.7[0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     Found ATLAS CMTCONFIG i686-slc5-gcc43-opt[0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     Using run directory: ./[0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     Extracting athena run configuration ... [0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     This can take a while since the athena autoconfiguration is called in the background to extract the jobOption configuration ... [0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     Set Athena run configuration to: {'input': {}, 'other': {}, 'output': {}}[0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     Copying RootCore packages to current dir ...[0;0m
[0;33mGanga.Core.GangaRepository         : WARNING  Removing dead file linappserv4.pp.rhul.ac.uk.1375101091171.4478.session.prep.metadata.locks[0;0m
[0;33mGanga.Core.GangaRepository         : WARNING  Removing dead file linappserv4.pp.rhul.ac.uk.1375101091171.4478.session.templates.metadata.locks[0;0m
[0;33mGanga.Core.GangaRepository         : WARNING  Removing dead file linappserv4.pp.rhul.ac.uk.1375101091171.4478.session.templates.locks[0;0m
[0;0mGanga.Core.GangaRepository         : INFO     Unimportant OSError in loop: [Errno 2] No such file or directory: '/nfs/scratch3/jblanco/gangadir-EL/repository/jblanco/LocalXML/6.0/sessions/linappserv4.pp.rhul.ac.uk.1375101091171.4478.session.templates.locks'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005433.EXT0._00007.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201556.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201556.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005433.EXT0._00007.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1078.t42.trf0.u0/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201556.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005433.EXT0._00007.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1078.t42.trf0.u0/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201556.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005433.EXT0._00007.hist-output.root'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005435.EXT0._00059.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201555.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201555.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005435.EXT0._00059.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1079.t42.trf0.u1/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201555.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005435.EXT0._00059.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1079.t42.trf0.u1/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201555.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005435.EXT0._00059.hist-output.root'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005437.EXT0._00086.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201494.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201494.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005437.EXT0._00086.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1080.t42.trf0.u2/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201494.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005437.EXT0._00086.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1080.t42.trf0.u2/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201494.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005437.EXT0._00086.hist-output.root'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005439.EXT0._00102.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201489.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201489.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005439.EXT0._00102.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1081.t42.trf0.u3/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201489.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005439.EXT0._00102.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1081.t42.trf0.u3/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201489.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005439.EXT0._00102.hist-output.root'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Registered container for Unit 4 of Transform 0: user.jayb88.20130709112655.skim_PeriodA.p1328_20130709112610.full_v3.id_42.skim_PeriodA.p1328_20130709112610.full_v3.0/[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Registered container for Unit 4 of Transform 0: user.jayb88.20130709112655.skim_PeriodA.p1328_20130709112610.full_v3.id_42/[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005444.EXT0._00118.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201351.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201351.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005444.EXT0._00118.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1083.t42.trf0.u5/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201351.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005444.EXT0._00118.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1083.t42.trf0.u5/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201351.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005444.EXT0._00118.hist-output.root'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005446.EXT0._00151.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201289.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201289.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005446.EXT0._00151.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1084.t42.trf0.u6/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201289.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005446.EXT0._00151.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1084.t42.trf0.u6/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201289.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005446.EXT0._00151.hist-output.root'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005448.EXT0._00160.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201280.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201280.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005448.EXT0._00160.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1085.t42.trf0.u7/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201280.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005448.EXT0._00160.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1085.t42.trf0.u7/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201280.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005448.EXT0._00160.hist-output.root'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005450.EXT0._00167.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201269.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201269.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005450.EXT0._00167.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1086.t42.trf0.u8/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201269.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005450.EXT0._00167.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1086.t42.trf0.u8/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201269.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005450.EXT0._00167.hist-output.root'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005452.EXT0._00221.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201257.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201257.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005452.EXT0._00221.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1087.t42.trf0.u9/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201257.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005452.EXT0._00221.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1087.t42.trf0.u9/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201257.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005452.EXT0._00221.hist-output.root'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005454.EXT0._00254.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201191.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201191.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005454.EXT0._00254.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1088.t42.trf0.u10/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201191.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005454.EXT0._00254.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1088.t42.trf0.u10/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201191.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005454.EXT0._00254.hist-output.root'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005456.EXT0._00268.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201190.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201190.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005456.EXT0._00268.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1089.t42.trf0.u11/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201190.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005456.EXT0._00268.hist-output.root user.jayb88.skim_PeriodA.p1328_20130709112610.full_v3.j1089.t42.trf0.u11/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodA.p1328_20130709112610.full_v3/elg/download/data12_8TeV.periodA.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00201190.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005456.EXT0._00268.hist-output.root'[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Exception occurred in task monitoring loop: <type 'exceptions.IndexError'> tuple index out of range
The offending task was paused.[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Full traceback:
 Traceback (most recent call last):
   File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/python/Ganga/GPIDev/Lib/Tasks/TaskRegistry.py", line 119, in _thread_main
    p.update()
   File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/python/Ganga/GPIDev/Lib/Tasks/ITask.py", line 80, in update
    if trf.update():
   File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/python/Ganga/GPIDev/Lib/Tasks/ITransform.py", line 186, in update
    if unit.update() and self.abort_loop_on_submit:
   File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/python/Ganga/GPIDev/Lib/Tasks/IUnit.py", line 178, in update
    if not self.copyOutput():
   File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/python/GangaAtlas/Lib/Tasks/AtlasUnit.py", line 360, in copyOutput
    for guid in dq2_list[0].keys():
 IndexError: tuple index out of range
[0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     gathering files under /nfs/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130729132955.v1/elg/inputsandbox[0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     Adding files to source tarball /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130729132955.v1/elg/jobO.47b547c1-3df5-40f3-b930-301473b235a6.tar[0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     Creating /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130729132955.v1/elg/jobO.47b547c1-3df5-40f3-b930-301473b235a6.tar ...[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005491.EXT0._00046.hist-output.root.5' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_NonPromptJPsi.p1328_20130709154550.full/elg/download/mc12_8TeV.208202.Pythia8B_AU2_CTEQ6L1_bb_Jpsimu6mu6.merge.NTUP_SMWZ.e1454_a159_a180_r3549_p1328/208202.Pythia8B_AU2_CTEQ6L1_bb_Jpsimu6mu6.merge.NTUP_SMWZ...[0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     Compressing to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130729132955.v1/elg/jobO.47b547c1-3df5-40f3-b930-301473b235a6.tar.gz ...[0;0m
[0;0mGanga.GangaAtlas.Lib.Athena        : INFO     Removing temporary RootCore submission directory /nfs/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130729132955.v1/elg/inputsandbox/__panda_rootCoreWorkDir ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_NonPromptJPsi.p1328_20130709154550.full/elg/download/mc12_8TeV.208202.Pythia8B_AU2_CTEQ6L1_bb_Jpsimu6mu6.merge.NTUP_SMWZ.e1454_a159_a180_r3549_p1328/208202.Pythia8B_AU2_CTEQ6L1_bb_Jpsimu6mu6.merge.NTUP_SMWZ -f user.jayb88.005491.EXT0._00046.hist-output.root.5 user.jayb88.skim_NonPromptJPsi.p1328_20130709154550.full.j1106.t44.trf0.u0/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_NonPromptJPsi.p1328_20130709154550.full/elg/download/mc12_8TeV.208202.Pythia8B_AU2_CTEQ6L1_bb_Jpsimu6mu6.merge.NTUP_SMWZ.e1454_a159_a180_r3549_p1328/208202.Pythia8B_AU2_CTEQ6L1_bb_Jpsimu6mu6.merge.NTUP_SMWZ -f user.jayb88.005491.EXT0._00046.hist-output.root.5 user.jayb88.skim_NonPromptJPsi.p1328_20130709154550.full.j1106.t44.trf0.u0/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_NonPromptJPsi.p1328_20130709154550.full/elg/download/mc12_8TeV.208202.Pythia8B_AU2_CTEQ6L1_bb_Jpsimu6mu6.merge.NTUP_SMWZ.e1454_a159_a180_r3549_p1328/208202.Pythia8B_AU2_CTEQ6L1_bb_Jpsimu6mu6.merge.NTUP_SMWZ/user.jayb88.005491.EXT0._00046.hist-output.root.5'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005495.EXT0._00056.hist-output.root.1' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PromptJPsi.p1328_20130709233724.full_v4/elg/download/mc12_8TeV.208002.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu6mu6.merge.NTUP_SMWZ.e1331_a159_a180_r3549_p1328/208002.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu6mu6.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PromptJPsi.p1328_20130709233724.full_v4/elg/download/mc12_8TeV.208002.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu6mu6.merge.NTUP_SMWZ.e1331_a159_a180_r3549_p1328/208002.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu6mu6.merge.NTUP_SMWZ -f user.jayb88.005495.EXT0._00056.hist-output.root.1 user.jayb88.skim_PromptJPsi.p1328_20130709233724.full_v4.j1109.t46.trf0.u0/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PromptJPsi.p1328_20130709233724.full_v4/elg/download/mc12_8TeV.208002.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu6mu6.merge.NTUP_SMWZ.e1331_a159_a180_r3549_p1328/208002.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu6mu6.merge.NTUP_SMWZ -f user.jayb88.005495.EXT0._00056.hist-output.root.1 user.jayb88.skim_PromptJPsi.p1328_20130709233724.full_v4.j1109.t46.trf0.u0/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PromptJPsi.p1328_20130709233724.full_v4/elg/download/mc12_8TeV.208002.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu6mu6.merge.NTUP_SMWZ.e1331_a159_a180_r3549_p1328/208002.Pythia8B_AU2_CTEQ6L1_pp_Jpsimu6mu6.merge.NTUP_SMWZ/user.jayb88.005495.EXT0._00056.hist-output.root.1'[0;0m
[0;0mGanga.GPIDev.Adapters              : INFO     Sending file object /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodD.p1328_20130729132955.v1/elg/jobO.47b547c1-3df5-40f3-b930-301473b235a6.tar.gz to shared directory[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005497.EXT0._00002.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodB.p1328_20130710105705.full_v4/elg/download/data12_8TeV.periodB.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00202660.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodB.p1328_20130710105705.full_v4/elg/download/data12_8TeV.periodB.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00202660.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005497.EXT0._00002.hist-output.root user.jayb88.skim_PeriodB.p1328_20130710105705.full_v4.j1110.t47.trf0.u0/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodB.p1328_20130710105705.full_v4/elg/download/data12_8TeV.periodB.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00202660.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005497.EXT0._00002.hist-output.root user.jayb88.skim_PeriodB.p1328_20130710105705.full_v4.j1110.t47.trf0.u0/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodB.p1328_20130710105705.full_v4/elg/download/data12_8TeV.periodB.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00202660.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005497.EXT0._00002.hist-output.root'[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Exception occurred in task monitoring loop: <type 'exceptions.IndexError'> tuple index out of range
The offending task was paused.[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Full traceback:
 Traceback (most recent call last):
   File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/python/Ganga/GPIDev/Lib/Tasks/TaskRegistry.py", line 119, in _thread_main
    p.update()
   File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/python/Ganga/GPIDev/Lib/Tasks/ITask.py", line 80, in update
    if trf.update():
   File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/python/Ganga/GPIDev/Lib/Tasks/ITransform.py", line 186, in update
    if unit.update() and self.abort_loop_on_submit:
   File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/python/Ganga/GPIDev/Lib/Tasks/IUnit.py", line 178, in update
    if not self.copyOutput():
   File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/Ganga/6.0.13/install/6.0.13/python/GangaAtlas/Lib/Tasks/AtlasUnit.py", line 360, in copyOutput
    for guid in dq2_list[0].keys():
 IndexError: tuple index out of range
[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005629.EXT0._00074.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodC.p1328_20130718133912.full_v1_/elg/download/data12_8TeV.periodC.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00207397.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodC.p1328_20130718133912.full_v1_/elg/download/data12_8TeV.periodC.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00207397.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005629.EXT0._00074.hist-output.root user.jayb88.skim_PeriodC.p1328_20130718133912.full_v1_.j1172.t49.trf0.u0/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodC.p1328_20130718133912.full_v1_/elg/download/data12_8TeV.periodC.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00207397.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005629.EXT0._00074.hist-output.root user.jayb88.skim_PeriodC.p1328_20130718133912.full_v1_.j1172.t49.trf0.u0/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodC.p1328_20130718133912.full_v1_/elg/download/data12_8TeV.periodC.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00207397.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005629.EXT0._00074.hist-output.root'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005633.EXT0._00170.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodC.p1328_20130718133912.full_v1_/elg/download/data12_8TeV.periodC.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00207332.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodC.p1328_20130718133912.full_v1_/elg/download/data12_8TeV.periodC.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00207332.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005633.EXT0._00170.hist-output.root user.jayb88.skim_PeriodC.p1328_20130718133912.full_v1_.j1174.t49.trf0.u1/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodC.p1328_20130718133912.full_v1_/elg/download/data12_8TeV.periodC.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00207332.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005633.EXT0._00170.hist-output.root user.jayb88.skim_PeriodC.p1328_20130718133912.full_v1_.j1174.t49.trf0.u1/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodC.p1328_20130718133912.full_v1_/elg/download/data12_8TeV.periodC.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00207332.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005633.EXT0._00170.hist-output.root'[0;0m
[0;0mGanga.GPIDev.Lib.Tasks             : INFO     Downloading 'user.jayb88.005637.EXT0._00242.hist-output.root' to /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodC.p1328_20130718133912.full_v1_/elg/download/data12_8TeV.periodC.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00207306.physics_Muons.merge.NTUP_SMWZ...[0;0m
[0;33mGanga.Utility                      : WARNING  exit status [1] of command source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/gangaDDMSetup.sh && dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodC.p1328_20130718133912.full_v1_/elg/download/data12_8TeV.periodC.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00207306.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005637.EXT0._00242.hist-output.root user.jayb88.skim_PeriodC.p1328_20130718133912.full_v1_.j1176.t49.trf0.u2/[0;0m
[0;33mGanga.Utility                      : WARNING  <first 4096 bytes of output>
Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;33mGanga.Utility                      : WARNING  <end of first 4096 bytes of output>[0;0m
[0;31mGanga.GangaAtlas.Lib.ATLASDataset  : ERROR    Error occured during dq2-get -L ROAMING -a -d -H /scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodC.p1328_20130718133912.full_v1_/elg/download/data12_8TeV.periodC.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00207306.physics_Muons.merge.NTUP_SMWZ -f user.jayb88.005637.EXT0._00242.hist-output.root user.jayb88.skim_PeriodC.p1328_20130718133912.full_v1_.j1176.t49.trf0.u2/ Traceback (most recent call last):
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/bin/dq2-get", line 12, in ?
    from dq2.clientapi.cli.Get import Get
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/__init__.py", line 21, in ?
    from dq2.clientapi.aspects.validation import wrap_package
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/clientapi/aspects/validation.py", line 12, in ?
    import dq2.info.TiersOfATLASValidator
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLASValidator.py", line 8, in ?
    import dq2.info.TiersOfATLAS
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/TiersOfATLAS.py", line 23, in ?
    from dq2.info.ATLASCache               import ATLASCache
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/DQ2Client/2.4.0_patch1/DQ2Clients/opt/dq2/lib/dq2/info/ATLASCache.py", line 234
    finally:
          ^
SyntaxError: invalid syntax
[0;0m
[0;31mGanga.GPIDev.Lib.Tasks             : ERROR    Error downloading '/scratch3/jblanco/SMTMiniNtuplesSubmitDir/skim_PeriodC.p1328_20130718133912.full_v1_/elg/download/data12_8TeV.periodC.physics_Muons.PhysCont.NTUP_SMWZ.grp14_v01_p1328_p1329/00207306.physics_Muons.merge.NTUP_SMWZ/user.jayb88.005637.EXT0._00242.hist-output.root'[0;0m
[0;0mGanga.GPI                          : INFO     
TaskID: 50
TaskContainer: user.jayb88.20130729133134.skim_PeriodD.p1328_20130729132955.v1.id_50/

COMMAND:
for tr in tasks(50).transforms: print "%(in)s: %(out)s " % {"in": tr.application.options, "out": tr.getContainerName()}

RESPONSE:
Active server running on this machine.
Active server running on this machine.
Could not connect to server on port 434343

